#!/usr/bin/env bash
#
# Guided setup for exshell's release credentials.
#
# Everything mechanical is automated; the three steps Apple and GitHub only
# expose through a browser are prompted for, then validated once you have
# dropped the file in. Every step is idempotent — re-running skips whatever
# already exists — so you can stop and resume at any point.
#
#   scripts/setup-credentials.sh status     what exists, what is missing
#   scripts/setup-credentials.sh import     import an existing .p12 and .p8
#   scripts/setup-credentials.sh csr        generate a signing request instead
#   scripts/setup-credentials.sh p12        build the .p12 from Apple's .cer
#   scripts/setup-credentials.sh asc        record the notarization key
#   scripts/setup-credentials.sh gpg        generate the repo signing key
#   scripts/setup-credentials.sh tokens     record the two GitHub tokens
#   scripts/setup-credentials.sh upload     push all secrets to GitHub
#   scripts/setup-credentials.sh verify     check secrets, DNS, Pages
#   scripts/setup-credentials.sh shred      securely delete the local copies
#
#   scripts/setup-credentials.sh all        run the sequence in order
#
# Already have the Apple certificate and notarization key? Start with
# `import` — it validates them, reads the signing identity out of the
# certificate, and skips the CSR entirely.
#
# Everything is written to .credentials/ (mode 0700, git-ignored).
set -euo pipefail

# Every file this script creates is secret by default.
umask 077

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
dir="$repo_root/.credentials"
manifest="$dir/manifest.env"

GH_REPO=${GH_REPO:-vanlabeke/exshell}
PAGES_HOST=${PAGES_HOST:-pkg.vanlabeke.dev}

# --- output helpers ----------------------------------------------------------

if [ -t 1 ]; then
	b=$(tput bold) dim=$(tput dim) r=$(tput sgr0)
	red=$(tput setaf 1) grn=$(tput setaf 2) ylw=$(tput setaf 3)
else
	b='' dim='' r='' red='' grn='' ylw=''
fi

say()  { printf '%s\n' "$*"; }
head1() { printf '\n%s%s%s\n' "$b" "$*" "$r"; }
ok()   { printf '  %s✓%s %s\n' "$grn" "$r" "$*"; }
miss() { printf '  %s·%s %s\n' "$dim" "$r" "$*"; }
warn() { printf '  %s!%s %s\n' "$ylw" "$r" "$*"; }
die()  { printf '\n%serror:%s %s\n' "$red" "$r" "$*" >&2; exit 1; }

# Prompt for a value that must not appear in the scrollback or in `ps`.
read_secret() {
	local prompt=$1 dest=$2 value
	printf '  %s: ' "$prompt"
	read -rs value
	printf '\n'
	[ -n "$value" ] || die "empty value, nothing written to $(basename "$dest")"
	printf '%s' "$value" >"$dest"
	chmod 600 "$dest"
}

read_plain() {
	local prompt=$1 value
	printf '  %s: ' "$prompt" >&2
	read -r value
	printf '%s' "$value"
}

# Wait for the user to place a downloaded file. Accepts a glob so the caller
# does not have to know Apple's exact filename.
await_file() {
	local glob=$1 label=$2 found
	while :; do
		# shellcheck disable=SC2086
		found=$(compgen -G "$glob" 2>/dev/null | head -1 || true)
		[ -n "$found" ] && { printf '%s' "$found"; return 0; }
		printf '\n  %sWaiting for %s%s\n  Move it to: %s\n  Press Return once it is there (or Ctrl-C to stop): ' \
			"$dim" "$label" "$r" "$dir"
		# A closed stdin (piped, or a non-interactive shell) must say so
		# rather than spin or die with an opaque `read` failure.
		read -r _ || die "stdin closed while waiting for $label — run this in a terminal"
	done
}

need() { command -v "$1" >/dev/null 2>&1 || die "$1 is required but not installed${2:+ — $2}"; }

# manifest holds NON-secret identifiers only, so it is safe to cat and to
# paste into a ticket. Secrets live in their own mode-0600 files.
manifest_set() {
	local key=$1 val=$2
	touch "$manifest"; chmod 600 "$manifest"
	if grep -q "^$key=" "$manifest" 2>/dev/null; then
		# Portable in-place edit: BSD and GNU sed disagree about -i.
		grep -v "^$key=" "$manifest" >"$manifest.tmp"
		mv "$manifest.tmp" "$manifest"
	fi
	printf '%s=%s\n' "$key" "$val" >>"$manifest"
}

manifest_get() {
	[ -f "$manifest" ] || return 0
	sed -n "s/^$1=//p" "$manifest" | tail -1
}

# --- init --------------------------------------------------------------------

cmd_init() {
	mkdir -p "$dir"
	chmod 700 "$dir"

	# Belt and braces: the .gitignore entry is committed, but a stray
	# `git add -f` or a fresh clone with an edited .gitignore should still
	# not be able to commit this directory.
	printf '*\n' >"$dir/.gitignore"

	cat >"$dir/README.txt" <<'TXT'
exshell release credentials
===========================

Generated by scripts/setup-credentials.sh. Everything here is secret except
manifest.env, which holds only identifiers.

  devid.key                 private key for the Apple signing certificate
  devid.certSigningRequest  the request you upload to Apple
  *.cer                     what Apple gives back
  devid.pem                 the same certificate, PEM-encoded
  Certificates.p12          key + certificate bundled for CI
  p12-password.txt          export password for the above
  AuthKey_*.p8              App Store Connect key for notarization
  gnupg/                    self-contained keyring for the repo signing key
  gpg-private.asc           exported private key (base64, for CI)
  gpg-passphrase.txt        its passphrase
  gpg-revoke.asc            revocation certificate — back this up
  token-tap.txt             PAT for the Homebrew tap repository
  token-packages.txt        PAT for the packages repository
  manifest.env              non-secret identifiers

These files are NOT a backup. This directory is git-ignored and lives on one
disk. Copy the contents into your password manager, then consider running
`scripts/setup-credentials.sh shred`.

Losing gpg-private.asc is the worst case: everyone who has already added the
apt repository must install a replacement key by hand before `apt update`
works again for them.
TXT
	chmod 600 "$dir/README.txt"
}

# --- what to do next ---------------------------------------------------------
#
# Prints complete instructions for the next thing that actually needs a human,
# rather than the name of a command to go and look up. Only three steps in this
# whole process cannot be automated; everything else the script has already
# done by the time this runs.

have_cer() { compgen -G "$dir/*.cer" >/dev/null 2>&1; }
have_p8()  { compgen -G "$dir/AuthKey_*.p8" >/dev/null 2>&1; }

manifest_complete() {
	[ -n "$(manifest_get MACOS_SIGN_IDENTITY)" ] &&
	[ -n "$(manifest_get AC_KEY_ID)" ] &&
	[ -n "$(manifest_get AC_ISSUER_ID)" ] &&
	[ -n "$(manifest_get GPG_KEY_ID)" ]
}

everything_local() {
	[ -s "$dir/Certificates.p12" ] && [ -s "$dir/p12-password.txt" ] &&
	have_p8 && [ -s "$dir/gpg-private.asc" ] &&
	[ -s "$dir/token-tap.txt" ] && [ -s "$dir/token-packages.txt" ] &&
	manifest_complete
}

print_next() {
	printf '\n%s──────────────────────────────────────────────────────────%s\n' "$dim" "$r"

	# 1. Apple signing certificate.
	if [ ! -s "$dir/Certificates.p12" ]; then
		if have_cer; then
			head1 "NEXT — nothing, this is automatic"
			cat <<EOF
Apple's certificate is here but the bundle has not been built. Run:

  ${b}scripts/setup-credentials.sh p12${r}
EOF
			return
		fi
		head1 "NEXT — the Apple signing certificate (needs a browser)"
		cat <<EOF
Apple has no API for issuing a Developer ID certificate, so this part is
manual. Two routes, depending on what you already have.

${b}If you already have a .p12 exported from Keychain Access${r}

  scripts/setup-credentials.sh import

  It asks for the file and its password, checks the password actually opens
  it, and reads the signing identity straight out of the certificate — so
  there is no chance of a typo in the "Developer ID Application: … (TEAMID)"
  string that CI has to match exactly.

${b}If you are starting from nothing${r}

  1. scripts/setup-credentials.sh csr

     Generates the private key and the signing request locally. The key never
     leaves this machine; Apple only sees the request.

  2. Open  https://developer.apple.com/account/resources/certificates/add

  3. Under ${b}Software${r}, pick ${b}Developer ID Application${r}.

     Not "Mac Development", not "Mac App Distribution". Only Developer ID can
     sign software distributed outside the App Store, which is what a Homebrew
     cask and a downloadable tarball are.

  4. Upload  $dir/devid.certSigningRequest

  5. Download the .cer into  $dir

  6. scripts/setup-credentials.sh p12

     Builds the bundle, and refuses if the certificate was not issued from
     this key — which is far cheaper to learn here than as an opaque codesign
     failure in CI.
EOF
		return
	fi

	# 2. Notarization key.
	if ! have_p8 || [ -z "$(manifest_get AC_ISSUER_ID)" ]; then
		head1 "NEXT — the notarization key (needs a browser)"
		cat <<EOF
This is a separate credential from the signing certificate: the certificate
signs, this authenticates the notarization request. Apple lets you download
it ${b}exactly once${r} — have your password manager open first.

  1. Open  https://appstoreconnect.apple.com/access/integrations/api

  2. Select ${b}Team Keys${r}, then ${b}+${r}

  3. Name it something like  notarization-ci

  4. Set access to ${b}Developer${r}. That is enough to notarize, and a CI
     credential should have nothing more.

  5. Generate, then download the AuthKey_*.p8 into  $dir

  6. Note the ${b}Key ID${r} (in the key's row) and the ${b}Issuer ID${r}
     (the UUID above the key list — shared by every key on the team).

  7. scripts/setup-credentials.sh asc

     It reads the Key ID off the filename and asks for the Issuer ID.
EOF
		return
	fi

	# 3. GPG key — automatic, but gnupg has to be installed.
	if [ ! -s "$dir/gpg-private.asc" ]; then
		head1 "NEXT — the repository signing key"
		if command -v gpg >/dev/null 2>&1; then
			cat <<EOF
Fully automatic. Run:

  ${b}scripts/setup-credentials.sh gpg${r}
EOF
		else
			cat <<EOF
gnupg is not installed, which is the only thing standing in the way:

  ${b}brew install gnupg${r}
  ${b}scripts/setup-credentials.sh gpg${r}

The script then generates the key, its passphrase, and its revocation
certificate with no further input. It uses rsa4096 rather than ed25519,
because rpm on older RHEL derivatives cannot verify ed25519 — and a signature
those systems reject is a repository they cannot install from.
EOF
		fi
		return
	fi

	# 4. GitHub tokens.
	if [ ! -s "$dir/token-tap.txt" ] || [ ! -s "$dir/token-packages.txt" ]; then
		head1 "NEXT — two GitHub tokens (needs a browser)"
		cat <<EOF
No API mints a personal access token, so this one is manual too.

The release runs inside $GH_REPO but has to write to two other
repositories. The automatic GITHUB_TOKEN is scoped to the repository it runs
in and cannot reach them — that is the only reason these exist.

Create each at  https://github.com/settings/personal-access-tokens/new

  ${b}Resource owner${r}      the ${b}vanlabeke${r} organization, not your user
                      account — otherwise the token cannot see the repos
  ${b}Repository access${r}   Only select repositories
  ${b}Permissions${r}         Contents: Read and write

  Token 1 → only  vanlabeke/homebrew-tap
  Token 2 → only  vanlabeke/packages

Two narrow tokens rather than one broad one: if the tap token leaks, the
package repository is unaffected.

Note the expiry dates. When a fine-grained token lapses, releases fail at the
publish step with a permissions error, months later and with no warning
beforehand — worth a calendar reminder a week before.

If the organization restricts token access, yours will sit in a ${b}pending
approval${r} state until an owner approves it. From the workflow's side that
looks identical to a permissions failure.

Then:

  ${b}scripts/setup-credentials.sh tokens${r}
EOF
		return
	fi

	# 5. Upload — automatic.
	if ! secrets_uploaded; then
		head1 "NEXT — nothing, this is automatic"
		cat <<EOF
Every credential is present locally. Push them to GitHub:

  ${b}scripts/setup-credentials.sh upload${r}
EOF
		return
	fi

	# 6. DNS — needs the registrar.
	if ! dig +short "$PAGES_HOST" >/dev/null 2>&1 || [ -z "$(dig +short "$PAGES_HOST" 2>/dev/null)" ]; then
		head1 "NEXT — one DNS record (needs Cloudflare)"
		cat <<EOF
GitHub's side is already done: Pages is enabled on vanlabeke/packages, the
repository is public, and the CNAME file is committed. Only the record itself
is missing.

In Cloudflare, on ${b}vanlabeke.dev${r}:

  Type    ${b}CNAME${r}
  Name    ${b}pkg${r}
  Target  ${b}vanlabeke.github.io${r}
  Proxy   ${b}DNS only${r}  (grey cloud, not orange)

${b}The proxy setting matters.${r} With Cloudflare proxying in front of Pages,
GitHub cannot complete the challenge that issues the TLS certificate, and the
domain sits unverified with HTTPS unavailable. You can enable the proxy later,
once Pages shows the certificate as issued.

${dim}vanlabeke.github.io not loading in a browser is expected and harmless —
there is no organization site repo behind it. It resolves correctly as a CNAME
target, which is all that is needed here.${r}

Then re-run:

  ${b}scripts/setup-credentials.sh verify${r}
EOF
		return
	fi

	# 7. Done.
	head1 "READY — cut the first release"
	cat <<EOF
Make the repository public first. The release workflow uses a macOS runner,
which bills at a ${b}10x minute multiplier${r} while the repository is private
and is free once it is public.

  gh repo edit $GH_REPO --visibility public --accept-visibility-change-consequences

  git tag v0.1.0
  git push origin v0.1.0
  gh run watch -R $GH_REPO

${b}Expect the first run to fail somewhere.${r} Two parts of this pipeline have
never executed: the apt/yum generation script needs Debian tooling that does
not exist on macOS, and the workflows cannot run without these credentials.
The configuration is verified — a local snapshot builds all fifteen artifacts
— but the CI paths are not. A failed run costs nothing but a re-tag:

  git tag -d v0.1.0 && git push origin :refs/tags/v0.1.0

Once it succeeds, verify as a stranger would:

  brew tap vanlabeke/tap && brew install --cask exshell
  exshell --version        # must print 0.1.0, not a v0.0.0-… pseudo-version

A pseudo-version there means the ldflags never reached the binary, and the
release is mislabelled even though everything else worked.

${b}Then put these in your password manager and consider 'shred':${r}
  Certificates.p12 + its password · AuthKey_*.p8 (Apple will not re-issue it)
  gpg-private.asc + passphrase + gpg-revoke.asc  ← the one that cannot be
  replaced cheaply: without it, every machine already trusting your apt
  repository needs a new key installed by hand.
EOF
}

secrets_uploaded() {
	command -v gh >/dev/null 2>&1 || return 1
	local present
	present=$(gh secret list -R "$GH_REPO" --json name -q '.[].name' 2>/dev/null || true)
	printf '%s\n' "$present" | grep -qx MACOS_CERT_P12 &&
	printf '%s\n' "$present" | grep -qx PACKAGES_TOKEN
}

# --- status ------------------------------------------------------------------

check() {
	local path=$1 label=$2
	if [ -s "$path" ]; then ok "$label"; else miss "$label"; fi
}

cmd_status() {
	cmd_init
	head1 "Local files in .credentials/"
	check "$dir/devid.key"                  "Apple private key            (devid.key)"
	check "$dir/devid.certSigningRequest"   "Signing request              (devid.certSigningRequest)"
	if compgen -G "$dir/*.cer" >/dev/null 2>&1; then
		ok   "Apple certificate            ($(basename "$(compgen -G "$dir/*.cer" | head -1)"))"
	else
		miss "Apple certificate            (drop the .cer here)"
	fi
	check "$dir/Certificates.p12"           "Signing bundle               (Certificates.p12)"
	check "$dir/p12-password.txt"           "Bundle password              (p12-password.txt)"
	if compgen -G "$dir/AuthKey_*.p8" >/dev/null 2>&1; then
		ok   "Notarization key             ($(basename "$(compgen -G "$dir/AuthKey_*.p8" | head -1)"))"
	else
		miss "Notarization key             (drop the AuthKey_*.p8 here)"
	fi
	check "$dir/gpg-private.asc"            "GPG private key              (gpg-private.asc)"
	check "$dir/gpg-revoke.asc"             "GPG revocation certificate   (gpg-revoke.asc)"
	check "$dir/token-tap.txt"              "Homebrew tap token           (token-tap.txt)"
	check "$dir/token-packages.txt"         "Packages token               (token-packages.txt)"

	head1 "Recorded identifiers"
	if [ -s "$manifest" ]; then
		sed 's/^/  /' "$manifest"
	else
		miss "none yet"
	fi

	print_next
	printf '\n'
}

# --- auto: do everything possible, then say what is left ---------------------
#
# The default. Runs every step that needs no human, in dependency order, then
# prints full instructions for the first thing that does.
cmd_auto() {
	cmd_init

	# Build the signing bundle if Apple's certificate has landed.
	if [ ! -s "$dir/Certificates.p12" ] && have_cer; then
		head1 "Building the signing bundle from Apple's certificate"
		cmd_p12 || true
	fi

	# Generate the repository signing key — no input needed beyond a default
	# identity, so AUTO=1 suppresses the prompt.
	if [ ! -s "$dir/gpg-private.asc" ] && command -v gpg >/dev/null 2>&1; then
		head1 "Generating the repository signing key"
		AUTO=1 cmd_gpg || true
	fi

	# Upload once everything is present.
	if everything_local && ! secrets_uploaded; then
		head1 "Uploading secrets"
		cmd_upload || true
	fi

	cmd_status
}

# --- 1. certificate signing request -----------------------------------------

cmd_csr() {
	cmd_init
	need openssl

	if [ -s "$dir/devid.certSigningRequest" ]; then
		ok "signing request already exists, keeping it"
		say "  ${dim}A new request would orphan the certificate issued from the old one.${r}"
		return 0
	fi

	head1 "Apple signing request"
	say "The private key is generated here and never leaves this machine."
	printf '\n'

	local name email country
	name=$(read_plain "Your name, as it should appear in the certificate")
	[ -n "$name" ] || die "a name is required"
	email=$(read_plain "Your email address")
	[ -n "$email" ] || die "an email address is required"
	country=$(read_plain "Two-letter country code [BE]")
	country=${country:-BE}

	openssl req -new -newkey rsa:2048 -nodes \
		-keyout "$dir/devid.key" \
		-out "$dir/devid.certSigningRequest" \
		-subj "/CN=$name/emailAddress=$email/C=$country" 2>/dev/null

	chmod 600 "$dir/devid.key" "$dir/devid.certSigningRequest"
	ok "wrote devid.key and devid.certSigningRequest"

	cat <<EOF

${b}Now do this in a browser${r}

  1. Open  https://developer.apple.com/account/resources/certificates/add
  2. Under ${b}Software${r}, choose ${b}Developer ID Application${r}
       (not "Mac Development", not "Mac App Distribution" — only Developer ID
        can sign software distributed outside the App Store)
  3. Upload  $dir/devid.certSigningRequest
  4. Download the resulting .cer into  $dir

Then run: ${b}scripts/setup-credentials.sh p12${r}
EOF
}

# --- 2. build the .p12 -------------------------------------------------------

cmd_p12() {
	cmd_init
	need openssl

	[ -s "$dir/devid.key" ] || die "no devid.key — run 'csr' first"

	if [ -s "$dir/Certificates.p12" ]; then
		ok "Certificates.p12 already exists, keeping it"
		return 0
	fi

	local cer
	cer=$(compgen -G "$dir/*.cer" 2>/dev/null | head -1 || true)
	if [ -z "$cer" ]; then
		cer=$(await_file "$dir/*.cer" "the .cer downloaded from Apple")
	fi
	ok "using $(basename "$cer")"

	# Apple serves DER; everything downstream wants PEM.
	openssl x509 -inform DER -in "$cer" -out "$dir/devid.pem" 2>/dev/null \
		|| openssl x509 -in "$cer" -out "$dir/devid.pem" 2>/dev/null \
		|| die "could not read $cer as a certificate"

	# Refuse to build a bundle whose halves do not belong together — this
	# fails loudly here rather than as an opaque codesign error in CI.
	local certmod keymod
	certmod=$(openssl x509 -noout -modulus -in "$dir/devid.pem" | openssl md5)
	keymod=$(openssl rsa -noout -modulus -in "$dir/devid.key" 2>/dev/null | openssl md5)
	[ "$certmod" = "$keymod" ] \
		|| die "this certificate was not issued from devid.key — wrong .cer, or the key was regenerated"
	ok "certificate matches the private key"

	local pass
	if [ -s "$dir/p12-password.txt" ]; then
		pass=$(cat "$dir/p12-password.txt")
	else
		pass=$(openssl rand -base64 24)
		printf '%s' "$pass" >"$dir/p12-password.txt"
		chmod 600 "$dir/p12-password.txt"
		ok "generated an export password (p12-password.txt)"
	fi

	openssl pkcs12 -export \
		-inkey "$dir/devid.key" -in "$dir/devid.pem" \
		-name "Developer ID Application" \
		-passout "pass:$pass" \
		-out "$dir/Certificates.p12"
	chmod 600 "$dir/Certificates.p12"
	ok "wrote Certificates.p12"

	# The identity string CI needs is the certificate's Common Name, which
	# Apple rewrites to include the Team ID.
	local subject identity team
	subject=$(openssl x509 -in "$dir/devid.pem" -noout -subject)
	identity=$(printf '%s' "$subject" | sed -n 's/.*CN *= *\([^,/]*\).*/\1/p' | sed 's/[[:space:]]*$//')
	if [ -n "$identity" ]; then
		manifest_set MACOS_SIGN_IDENTITY "$identity"
		ok "identity: $identity"
		case "$identity" in
			"Developer ID Application:"*) ;;
			*) warn "that is not a Developer ID Application certificate"
			   warn "only Developer ID can sign software distributed outside the App Store" ;;
		esac
		team=$(printf '%s' "$identity" | sed -n 's/.*(\([A-Z0-9]*\)).*/\1/p')
		[ -n "$team" ] && { manifest_set APPLE_TEAM_ID "$team"; ok "team ID: $team"; }
	else
		warn "could not parse the identity from: $subject"
		warn "set MACOS_SIGN_IDENTITY in $manifest by hand"
	fi

	print_next
}

# --- 3. notarization key -----------------------------------------------------

cmd_asc() {
	cmd_init

	local p8
	p8=$(compgen -G "$dir/AuthKey_*.p8" 2>/dev/null | head -1 || true)

	if [ -z "$p8" ]; then
		cat <<EOF

${b}App Store Connect API key${r}

This authenticates notarization. It is a different credential from the
signing certificate, and Apple lets you download it ${b}exactly once${r}.

  1. Open  https://appstoreconnect.apple.com/access/integrations/api
  2. Select ${b}Team Keys${r}, then ${b}+${r}
  3. Name it something like  notarization-ci
  4. Set access to ${b}Developer${r} — enough to notarize, and nothing more
  5. Generate, then download the AuthKey_*.p8 into  $dir
EOF
		p8=$(await_file "$dir/AuthKey_*.p8" "the AuthKey_*.p8 from App Store Connect")
	fi
	chmod 600 "$p8"
	ok "using $(basename "$p8")"

	# The filename carries the Key ID, so offer it as the default.
	local guessed key_id issuer
	guessed=$(basename "$p8" | sed -n 's/^AuthKey_\(.*\)\.p8$/\1/p')

	key_id=$(manifest_get AC_KEY_ID)
	if [ -z "$key_id" ]; then
		key_id=$(read_plain "Key ID [$guessed]")
		key_id=${key_id:-$guessed}
		[ -n "$key_id" ] || die "a Key ID is required"
		manifest_set AC_KEY_ID "$key_id"
	fi
	ok "key ID: $key_id"

	issuer=$(manifest_get AC_ISSUER_ID)
	if [ -z "$issuer" ]; then
		say "  ${dim}The Issuer ID is the UUID above the key list on that page.${r}"
		issuer=$(read_plain "Issuer ID")
		[ -n "$issuer" ] || die "an Issuer ID is required"
		manifest_set AC_ISSUER_ID "$issuer"
	fi
	ok "issuer ID: $issuer"

	print_next
}

# --- 4. GPG signing key ------------------------------------------------------

cmd_gpg() {
	cmd_init
	need gpg "install it with: brew install gnupg"

	if [ -s "$dir/gpg-private.asc" ]; then
		ok "gpg-private.asc already exists, keeping it"
		say "  ${dim}Replacing this key breaks apt for everyone who already trusts it.${r}"
		return 0
	fi

	head1 "Repository signing key"

	# A self-contained keyring: this must not depend on, or disturb, your
	# personal ~/.gnupg.
	local gnupghome="$dir/gnupg"
	mkdir -p "$gnupghome"
	chmod 700 "$gnupghome"
	export GNUPGHOME="$gnupghome"

	local uid pass
	if [ -n "${AUTO:-}" ]; then
		uid="vanlabeke packages <packages@vanlabeke.dev>"
	else
		uid=$(read_plain "Key identity [vanlabeke packages <packages@vanlabeke.dev>]")
		uid=${uid:-"vanlabeke packages <packages@vanlabeke.dev>"}
	fi

	pass=$(openssl rand -base64 24)
	printf '%s' "$pass" >"$dir/gpg-passphrase.txt"
	chmod 600 "$dir/gpg-passphrase.txt"
	ok "generated a passphrase (gpg-passphrase.txt)"

	# rsa4096, not ed25519: rpm on older RHEL derivatives cannot verify
	# ed25519 signatures, and a signature those systems reject is a
	# repository they cannot install from.
	#
	# No expiry: an expired repository key breaks `apt update` on every
	# machine that already trusts it, and each user then has to install the
	# replacement by hand. Revoking stays available; un-expiring does not.
	gpg --batch --pinentry-mode loopback --passphrase "$pass" \
		--quick-generate-key "$uid" rsa4096 sign never

	local key_id
	key_id=$(gpg --list-secret-keys --with-colons \
		| awk -F: '/^fpr:/ { print $10; exit }')
	[ -n "$key_id" ] || die "key generated but its fingerprint could not be read"
	manifest_set GPG_KEY_ID "$key_id"
	ok "key: $key_id"

	# base64 so the armored key survives being a GitHub secret value.
	gpg --batch --pinentry-mode loopback --passphrase "$pass" \
		--export-secret-keys --armor "$key_id" | base64 >"$dir/gpg-private.asc"
	chmod 600 "$dir/gpg-private.asc"
	ok "exported gpg-private.asc (base64)"

	gpg --armor --export "$key_id" >"$dir/gpg-public.asc"
	ok "exported gpg-public.asc"

	local revoc
	revoc=$(compgen -G "$gnupghome/openpgp-revocs.d/*.rev" 2>/dev/null | head -1 || true)
	if [ -n "$revoc" ]; then
		cp "$revoc" "$dir/gpg-revoke.asc"
		chmod 600 "$dir/gpg-revoke.asc"
		ok "saved gpg-revoke.asc — back this up, it is your only way to revoke"
	else
		warn "no revocation certificate found under $gnupghome/openpgp-revocs.d/"
	fi

	print_next
}

# --- 5. GitHub tokens --------------------------------------------------------

cmd_tokens() {
	cmd_init

	if [ -s "$dir/token-tap.txt" ] && [ -s "$dir/token-packages.txt" ]; then
		ok "both tokens already recorded"
		return 0
	fi

	cat <<EOF

${b}Two fine-grained GitHub tokens${r}

The release runs in $GH_REPO but must write to two other repositories. The
automatic GITHUB_TOKEN is scoped to its own repository and cannot reach them,
which is the only reason these exist.

Create each at  https://github.com/settings/personal-access-tokens/new

  Resource owner       the ${b}vanlabeke${r} organization (not your user)
  Repository access    Only select repositories
  Permissions          Contents: Read and write

  Token 1 → only  vanlabeke/homebrew-tap
  Token 2 → only  vanlabeke/packages

Note each expiry date: when a token lapses, releases fail at the publish step
with a permissions error and no prior warning.
EOF

	if [ ! -s "$dir/token-tap.txt" ]; then
		printf '\n'
		read_secret "Paste the homebrew-tap token (hidden)" "$dir/token-tap.txt"
		ok "saved token-tap.txt"
	fi
	if [ ! -s "$dir/token-packages.txt" ]; then
		read_secret "Paste the packages token (hidden)" "$dir/token-packages.txt"
		ok "saved token-packages.txt"
	fi

	local exp
	exp=$(read_plain "Expiry date for these tokens, for your notes (YYYY-MM-DD, optional)")
	[ -n "$exp" ] && manifest_set TOKEN_EXPIRY "$exp"

	print_next
}

# --- 6. upload ---------------------------------------------------------------

cmd_upload() {
	cmd_init
	need gh
	gh auth status >/dev/null 2>&1 || die "gh is not authenticated — run: gh auth login"

	head1 "Uploading secrets to $GH_REPO"

	local missing=()
	[ -s "$dir/Certificates.p12" ]   || missing+=("Certificates.p12 (run 'p12')")
	[ -s "$dir/p12-password.txt" ]   || missing+=("p12-password.txt (run 'p12')")
	[ -s "$dir/gpg-private.asc" ]    || missing+=("gpg-private.asc (run 'gpg')")
	[ -s "$dir/token-tap.txt" ]      || missing+=("token-tap.txt (run 'tokens')")
	[ -s "$dir/token-packages.txt" ] || missing+=("token-packages.txt (run 'tokens')")
	compgen -G "$dir/AuthKey_*.p8" >/dev/null 2>&1 || missing+=("AuthKey_*.p8 (run 'asc')")

	local identity key_id issuer gpg_key
	identity=$(manifest_get MACOS_SIGN_IDENTITY)
	key_id=$(manifest_get AC_KEY_ID)
	issuer=$(manifest_get AC_ISSUER_ID)
	gpg_key=$(manifest_get GPG_KEY_ID)
	[ -n "$identity" ] || missing+=("MACOS_SIGN_IDENTITY in manifest.env")
	[ -n "$key_id" ]   || missing+=("AC_KEY_ID in manifest.env")
	[ -n "$issuer" ]   || missing+=("AC_ISSUER_ID in manifest.env")
	[ -n "$gpg_key" ]  || missing+=("GPG_KEY_ID in manifest.env")

	if [ ${#missing[@]} -gt 0 ]; then
		say "Cannot upload yet — still missing:"
		# One printf per item: a multi-placeholder format reuses itself
		# across an expanded array and interleaves the columns.
		local item
		for item in "${missing[@]}"; do miss "$item"; done
		die "run the steps above first, or 'status' to see where you are"
	fi

	local p8
	p8=$(compgen -G "$dir/AuthKey_*.p8" | head -1)

	set_secret() {
		local name=$1
		gh secret set "$name" -R "$GH_REPO" >/dev/null
		ok "$name"
	}

	base64 -i "$dir/Certificates.p12" | set_secret MACOS_CERT_P12
	set_secret MACOS_CERT_PASSWORD <"$dir/p12-password.txt"
	printf '%s' "$identity" | set_secret MACOS_SIGN_IDENTITY

	base64 -i "$p8" | set_secret AC_KEY_P8
	printf '%s' "$key_id" | set_secret AC_KEY_ID
	printf '%s' "$issuer" | set_secret AC_ISSUER_ID

	set_secret GPG_PRIVATE_KEY <"$dir/gpg-private.asc"
	printf '%s' "$gpg_key" | set_secret GPG_KEY_ID
	if [ -s "$dir/gpg-passphrase.txt" ]; then
		set_secret GPG_PASSPHRASE <"$dir/gpg-passphrase.txt"
	else
		printf '' | set_secret GPG_PASSPHRASE
	fi

	set_secret HOMEBREW_TAP_TOKEN <"$dir/token-tap.txt"
	set_secret PACKAGES_TOKEN <"$dir/token-packages.txt"

	print_next
}

# --- 7. verify ---------------------------------------------------------------

cmd_verify() {
	need gh

	local expected=(
		MACOS_CERT_P12 MACOS_CERT_PASSWORD MACOS_SIGN_IDENTITY
		AC_KEY_P8 AC_KEY_ID AC_ISSUER_ID
		GPG_PRIVATE_KEY GPG_KEY_ID GPG_PASSPHRASE
		HOMEBREW_TAP_TOKEN PACKAGES_TOKEN
	)

	head1 "Secrets on $GH_REPO"
	local present rc=0
	present=$(gh secret list -R "$GH_REPO" --json name -q '.[].name' 2>/dev/null || true)
	for s in "${expected[@]}"; do
		if printf '%s\n' "$present" | grep -qx "$s"; then ok "$s"; else miss "$s"; rc=1; fi
	done

	head1 "Repositories"
	for repo in "$GH_REPO" vanlabeke/homebrew-tap vanlabeke/packages; do
		if gh repo view "$repo" --json visibility -q .visibility >/dev/null 2>&1; then
			ok "$repo ($(gh repo view "$repo" --json visibility -q .visibility))"
		else
			miss "$repo unreachable"; rc=1
		fi
	done

	head1 "DNS and Pages for $PAGES_HOST"
	local ips
	ips=$(dig +short "$PAGES_HOST" 2>/dev/null | tr '\n' ' ' || true)
	if [ -n "$ips" ]; then
		ok "resolves: $ips"
		local code
		code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "https://$PAGES_HOST" || true)
		case "$code" in
			200) ok  "https://$PAGES_HOST responds 200" ;;
			000) warn "no HTTPS response yet — the certificate can take a while after the DNS record appears" ;;
			*)   warn "https://$PAGES_HOST responded $code" ;;
		esac
	else
		miss "$PAGES_HOST does not resolve — add a CNAME to vanlabeke.github.io (DNS only, not proxied)"
		rc=1
	fi

	head1 "macOS signing identity"
	local identity
	identity=$(manifest_get MACOS_SIGN_IDENTITY)
	if [ -n "$identity" ]; then ok "$identity"; else miss "not recorded"; rc=1; fi

	printf '\n'
	if [ "$rc" -eq 0 ]; then
		say "${grn}Ready.${r} Make the repository public, then tag:"
		say "  gh repo edit $GH_REPO --visibility public --accept-visibility-change-consequences"
		say "  git tag v0.1.0 && git push origin v0.1.0"
	else
		say "${ylw}Not ready yet${r} — see the gaps above."
	fi
	return "$rc"
}

# --- 8. shred ----------------------------------------------------------------

cmd_shred() {
	[ -d "$dir" ] || { ok "nothing to shred"; return 0; }

	cat <<EOF

${b}${red}This permanently deletes every local credential.${r}

  $dir

Only do this once all of the following are true:

  · the secrets are uploaded  (scripts/setup-credentials.sh verify)
  · the .p12 and its password are in your password manager
  · the AuthKey_*.p8 is in your password manager — Apple will not
    let you download it a second time
  · gpg-private.asc, its passphrase, and gpg-revoke.asc are in your
    password manager

The GPG key is the one that cannot be replaced cheaply: without it, every
machine that already trusts your apt repository needs a new key installed
by hand.
EOF
	printf "\nType %sshred%s to confirm: " "$b" "$r"
	local answer
	read -r answer
	[ "$answer" = "shred" ] || { say "Cancelled — nothing deleted."; return 0; }

	# Overwrite before unlinking where the tool exists; on APFS this is
	# best-effort anyway, which is why the password-manager copy matters.
	if command -v gshred >/dev/null 2>&1; then
		find "$dir" -type f -exec gshred -u {} + 2>/dev/null || true
	else
		find "$dir" -type f -exec rm -P {} + 2>/dev/null \
			|| find "$dir" -type f -delete
	fi
	rm -rf "$dir"
	ok "deleted $dir"
}

# --- import already-issued Apple credentials ---------------------------------
#
# For the common case where the certificate was exported from Keychain Access
# and the notarization key already downloaded — no CSR needed, and no reason
# to issue a second certificate.
cmd_import() {
	cmd_init
	need openssl

	head1 "Import existing Apple credentials"

	# --- the .p12 ---
	if [ -s "$dir/Certificates.p12" ]; then
		ok "Certificates.p12 already imported"
	else
		local src pass subject identity team
		src=$(read_plain "Path to your .p12 (drag the file into this terminal)")
		src=${src//\\ / }                       # un-escape a dragged path
		src=$(eval printf '%s' "\"$src\"")      # expand a leading ~
		[ -s "$src" ] || die "no such file: $src"

		printf '  %s: ' "Its export password (hidden)"
		read -rs pass
		printf '\n'

		# Validate before copying: a wrong password here is far cheaper to
		# discover than as an opaque keychain-import failure in CI.
		openssl pkcs12 -in "$src" -passin "pass:$pass" -noout -legacy 2>/dev/null \
			|| openssl pkcs12 -in "$src" -passin "pass:$pass" -noout 2>/dev/null \
			|| die "could not open that .p12 — wrong password, or not a PKCS#12 file"
		ok "password accepted"

		cp "$src" "$dir/Certificates.p12"
		printf '%s' "$pass" >"$dir/p12-password.txt"
		chmod 600 "$dir/Certificates.p12" "$dir/p12-password.txt"
		ok "imported Certificates.p12"

		# Pull the identity string out of the bundled certificate rather than
		# asking for it — it has to match byte for byte, and retyping
		# "Developer ID Application: Name (TEAMID)" is exactly where a typo
		# would go unnoticed until codesign failed.
		subject=$(openssl pkcs12 -in "$src" -passin "pass:$pass" -clcerts -nokeys -legacy 2>/dev/null \
			| openssl x509 -noout -subject 2>/dev/null || true)
		[ -n "$subject" ] || subject=$(openssl pkcs12 -in "$src" -passin "pass:$pass" -clcerts -nokeys 2>/dev/null \
			| openssl x509 -noout -subject 2>/dev/null || true)

		identity=$(printf '%s' "$subject" | sed -n 's/.*CN *= *\([^,/]*\).*/\1/p' | sed 's/[[:space:]]*$//')
		if [ -n "$identity" ]; then
			manifest_set MACOS_SIGN_IDENTITY "$identity"
			ok "identity: $identity"
			case "$identity" in
				"Developer ID Application:"*) ;;
				*) warn "that does not look like a Developer ID Application certificate"
				   warn "only Developer ID can sign software distributed outside the App Store" ;;
			esac
			team=$(printf '%s' "$identity" | sed -n 's/.*(\([A-Z0-9]*\)).*/\1/p')
			[ -n "$team" ] && { manifest_set APPLE_TEAM_ID "$team"; ok "team ID: $team"; }
		else
			warn "could not read the identity from the certificate"
			identity=$(read_plain "Paste it from: security find-identity -v -p codesigning")
			[ -n "$identity" ] && manifest_set MACOS_SIGN_IDENTITY "$identity"
		fi
	fi

	# --- the .p8 ---
	if compgen -G "$dir/AuthKey_*.p8" >/dev/null 2>&1; then
		ok "notarization key already imported"
	else
		local p8src base
		p8src=$(read_plain "Path to your AuthKey_*.p8")
		p8src=${p8src//\\ / }
		p8src=$(eval printf '%s' "\"$p8src\"")
		[ -s "$p8src" ] || die "no such file: $p8src"
		grep -q "PRIVATE KEY" "$p8src" || die "$p8src does not look like a .p8 private key"

		base=$(basename "$p8src")
		case "$base" in
			AuthKey_*.p8) ;;
			*) base="AuthKey_$(basename "$p8src" .p8).p8" ;;
		esac
		cp "$p8src" "$dir/$base"
		chmod 600 "$dir/$base"
		ok "imported $base"
	fi

	cmd_asc
}

# --- all ---------------------------------------------------------------------

cmd_all() {
	if [ -s "$dir/Certificates.p12" ] || [ -n "${IMPORT:-}" ]; then
		cmd_import
	else
		cmd_csr
		cmd_p12
		cmd_asc
	fi
	cmd_gpg
	cmd_tokens
	cmd_upload
	cmd_verify
}

usage() {
	# Print the header comment block, stopping at the first line of code —
	# a fixed line range silently spills source into the help text as soon
	# as the header grows.
	awk 'NR>2 { if (/^#/) { sub(/^# ?/, ""); print } else { exit } }' "${BASH_SOURCE[0]}"
	exit "${1:-0}"
}

case "${1:-auto}" in
	auto)    cmd_auto ;;
	status)  cmd_status ;;
	import)  cmd_import ;;
	csr)     cmd_csr ;;
	p12)     cmd_p12 ;;
	asc)     cmd_asc ;;
	gpg)     cmd_gpg ;;
	tokens)  cmd_tokens ;;
	upload)  cmd_upload ;;
	verify)  cmd_verify ;;
	shred)   cmd_shred ;;
	all)     cmd_all ;;
	-h|--help|help) usage 0 ;;
	*)       printf 'unknown command: %s\n\n' "$1" >&2; usage 2 ;;
esac
